/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonGroup: typeof import('./src/components/aside/ButtonGroup.vue')['default']
    EditInput: typeof import('./src/components/aside/EditInput.vue')['default']
    Editor: typeof import('./src/components/content/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    FileItem: typeof import('./src/components/aside/FileItem.vue')['default']
    FileList: typeof import('./src/components/aside/FileList.vue')['default']
    SearchFile: typeof import('./src/components/aside/SearchFile.vue')['default']
    Tabs: typeof import('./src/components/content/Tabs.vue')['default']
  }
}
