export enum IPC_AIP {
  GET_FILE_PATH = 'GET_FILE_PATH', // 获取文件路径
  SAVED_FILE = 'SAVED_FILE',
  UPDATED_FILE_NAME = 'UPDATED_FILE_NAME',
  EDIT_FILE = 'EDIT_FILE',
  DELETE_FILE = 'DELETE_FILE',
  READ_FILE = 'READ_FILE',
  SHOW_MESSAGE = 'SHOW_MESSAGE_BOX',
  GET_STORE_VALUE = 'GET_STORE_VALUE',
  SET_STORE_VALUE = 'SET_STORE_VALUE',
}
